### ISSUE TITLE
Error in addon for chrome and mozzila

### ISSUE THREAD

**Issue by ArinLP** [sag-enhanced/browser-extension#2]
Hello, I have a problem with your script, it reports me an error through which your generator does not work. (photo)
![err](https://user-images.githubusercontent.com/97413830/205071028-a9fbb3b3-3d85-4010-9c79-157c576e6503.png)

**Comment by Le0Developer** [comment]
1. Not an error, it's a warning
2. It's because the same extension supports both Firefox and Chorme and that option is required for Firefox.
