### ISSUE TITLE
Can't install version 9 on chrome or firefox

### ISSUE THREAD

**Issue by udisun** [sag-enhanced/browser-extension#3]
following the instructions for firefox results in the site not being able to identify the extension:
![image](https://github.com/sag-enhanced/browser-extension/assets/950100/4c557b96-1b1d-4d2a-bd7a-69b2280e90d6)
![image](https://github.com/sag-enhanced/browser-extension/assets/950100/96ad2faf-0487-460b-9fc5-7d9b325b8875)

following the instructions for chrome and trying to load unpacked the extension you get an error:
![image](https://github.com/sag-enhanced/browser-extension/assets/950100/659e02d5-70a6-4bd1-88bf-b4e50b956bea)

If I try to load unpacked the `static` folder inside the extension source I get this error:
![image](https://github.com/sag-enhanced/browser-extension/assets/950100/5202a42b-2c87-49f1-810b-f71196a4029b)

**Comment by Le0Developer** [comment]
v9 is for https://sage.party, the new domain.
For sage.leodev.xyz you need to use v8.
sage.leodev.xyz will redirect to the new domain at the end of the month.

**Comment by udisun** [comment]
@Le0Developer what about chrome extension that cannot be installed?

**Comment by Le0Developer** [comment]
Download the `sage-chromium.zip` file
