### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by dumbasPL** [sag-enhanced/browser-extension#4]
It seems like this repository lacks a `LICENSE` file. Is this intentional? If not please add one. If you don't know what to pick and the goal is to simply release the software without any restrictions then the MIT license is a good and popular choice.

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by Le0Developer** [comment]
This is intentional. The purpose of this repository is to provide transparency into the extension running in your browser.
